language: java
script: mvn clean test
notifications:
  slack:
    on_success: always
    on_failure: always
  email:
    - airlink@gmail.com
    - btao.cn@gmail.com

jdk:
  - oraclejdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:report
