security:
  whiteList:
    - "/entrance"
    - "/publicKey"
    - "/registration"
    - "/login"
    - "/passwordRetrievalApplication"
    - "/{userName}/passwordResetApplication"
    - "/{userName}/password"
    - "/unauthorised"
    - "/error"
    - "/favicon.ico"
